### PR TITLE
Do not rely on a global Buffer

### PR DESCRIPTION
**Pull request by kalinkrustev**
Improve browser handling by not relying on a global Buffer

### CODE REVIEW

**Comment by jdesboeufs** [comment]
And what about package [is-buffer](https://github.com/feross/is-buffer)?
Libraries depending on `readable-stream` and then `core-util-is` still need to wrap `Buffer` in `browserify` bundles.

**Comment by kalinkrustev** [comment]
In my case, I am using [lasso](https://github.com/lasso-js/lasso), which does not handle the Buffer global while bundling. I cannot switch to is-buffer module, as my actual dependency relies on readable-stream.

**Comment by jdesboeufs** [comment]
Yes but `core-util-is` could rely on `is-buffer`.

**Comment by darlanalves** [comment]
@isaacs Any chance on changing this `isBuffer` method? I spent a long time trying to figure out where rollup was failing to identify the Buffer import and ended up in this same issue. 

I saw a different approach on node core module exported for browserify here:

https://github.com/alexgorbatchev/node-browser-builtins/blob/master/builtin/util.js#L465

cc @kalinkrustev @jdesboeufs Check the link too :)
Using is-buffer would be the best way maybe. Works in both browser and Node.

**Comment by SachaG** [comment]
I also just ran into the same issue. It would be great if this PR could be merged!

**Comment by benjamn** [comment]
This is especially important for client-side bundlers that provide a `Buffer` polyfill, because it's much easier to detect the `require("buffer")` dependency than to tell that `Buffer` is being referenced as a global variable.

**Comment by JulianKingman** [comment]
@isaacs Anything preventing merging of this PR?

**Comment by achingbrain** [comment]
It would be great if this could be merged, this bites us all the time.

**Comment by mhemken-nyt** [comment]
"Be nice if this was merged."
-- Some dude in the year 2021

**Comment by kalinkrustev** [comment]
🎉

**Pull request closed without merging**
